"""empty message

Revision ID: 065c7f83a6e7
Revises: fb926a815626
Create Date: 2022-05-30 11:55:51.806902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '065c7f83a6e7'
down_revision = 'fb926a815626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
