"""empty message

Revision ID: 4bd6c093e02a
Revises: f0625fe81474
Create Date: 2022-05-30 13:36:54.762042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd6c093e02a'
down_revision = 'f0625fe81474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', name='crudenum'), nullable=True),
    sa.Column('story', sa.String(length=280), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stories')
    sa_enum = sa.Enum(name='crudenum')
    sa_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
